version: '3'

services:
    nginx:
        image: nginx
        container_name: nginx
        ports: 
            - 80:80
        volumes: 
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        restart: always
        
    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./hot_reload
        container_name: frontend
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - "/frontend/node_modules"
            - "./hot_reload:/frontend"
    
