apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo-deployment
  labels:
    type: mongo

spec:
  template:
    metadata:
      labels:
        type: mongo

    spec:
      containers:
        - name: mongo-pod
          image: mongo
          ports:
          - containerPort: 27017
          env:
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: MONGO_PORT

            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: MONGO_DATABASE


  replicas: 1
  selector:
    matchLabels:
      type: mongo
