apiVersion: v1
kind: PersistentVolume

metadata:
  name: mongo-pv
    
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo-data"